root: ./

​structure:
  moralis: README.md
  summary: SUMMARY.md​

redirects:
  moralis-server/getting-started: moralis-dapp/getting-started/README.md
  moralis-server/getting-started/create-a-moralis-server: moralis-dapp/getting-started/create-a-moralis-dapp.md
  moralis-server/connect-the-sdk: moralis-dapp/connect-the-sdk/README.md
  moralis-server/connect-the-sdk/connect-with-js: moralis-dapp/connect-the-sdk/connect-with-js.md
  moralis-server/connect-the-sdk/connect-with-react: moralis-dapp/connect-the-sdk/connect-with-react.md
  moralis-server/connect-the-sdk/connect-using-node: moralis-dapp/connect-the-sdk/connect-using-node.md
  moralis-server/connect-the-sdk/connect-with-unity: moralis-dapp/connect-the-sdk/connect-with-unity.md
  moralis-server/connect-the-sdk/boilerplate-projects: moralis-dapp/connect-the-sdk/boilerplate-projects.md
  moralis-server/users: moralis-dapp/users/README.md
  moralis-server/users/crypto-login: moralis-dapp/users/crypto-login.md
  moralis-server/users/crypto-login/metamask: moralis-dapp/users/crypto-login/metamask.md
  moralis-server/users/crypto-login/walletconnect: moralis-dapp/users/crypto-login/walletconnect.md
  moralis-server/users/crypto-login/web3Auth: moralis-dapp/users/crypto-login/web3Auth.md
  moralis-server/users/crypto-login/magic: moralis-dapp/users/crypto-login/magic.md
  moralis-server/users/crypto-login/custom-auth-any-eip1193-provider: moralis-dapp/users/crypto-login/custom-auth-any-eip1193-provider.md
  moralis-server/users/crypto-login/phantom-solana: moralis-dapp/users/crypto-login/phantom-solana.md
  moralis-server/users/crypto-login/sign-in-message: moralis-dapp/users/crypto-login/sign-in-message.md
  moralis-server/users/email-login: moralis-dapp/users/email-login/README.md
  moralis-server/users/email-login/sending-email: moralis-dapp/users/email-login/sending-email.md
  moralis-server/users/merging-addresses: moralis-dapp/users/merging-addresses.md
  moralis-server/users/current-user: moralis-dapp/users/current-user.md
  moralis-server/users/delete-user: moralis-dapp/users/delete-user.md
  moralis-server/users/security-for-other-objects: moralis-dapp/users/security-for-other-objects.md
  moralis-server/users/sessions: moralis-dapp/users/sessions.md
  moralis-server/sending-assets: moralis-dapp/sending-assets/README.md
  moralis-server/sending-assets/transfer-eth: moralis-dapp/sending-assets/transfer-eth.md
  moralis-server/sending-assets/transfer-tokens: moralis-dapp/sending-assets/transfer-tokens.md
  moralis-server/sending-assets/transfer-nfts: moralis-dapp/sending-assets/transfer-nfts.md
  moralis-server/sending-assets/resolve-transfer: moralis-dapp/sending-assets/resolve-transfer.md
  moralis-server/web3-sdk/README: moralis-dapp/web3-sdk/README.md
  moralis-server/web3-sdk/supported-chains: moralis-dapp/web3-sdk/supported-chains.md
  moralis-server/web3-sdk/native: moralis-dapp/web3-sdk/native.md
  moralis-server/web3-sdk/account: moralis-dapp/web3-sdk/account.md
  moralis-server/web3-sdk/token: moralis-dapp/web3-sdk/token.md
  moralis-server/web3-sdk/defi-new: moralis-dapp/web3-sdk/defi-new.md
  moralis-server/web3-sdk/ipfs-storage-new: moralis-dapp/web3-sdk/ipfs-storage-new.md
  moralis-server/web3-sdk/resolve: moralis-dapp/web3-sdk/resolve.md
  moralis-server/web3-sdk/moralis-web3-api-rest: moralis-dapp/web3-sdk/moralis-web3-api-rest.md
  moralis-server/web3-sdk/nft-api: moralis-dapp/web3-sdk/nft-api.md
  moralis-server/web3-sdk/rate-limit: moralis-dapp/web3-sdk/rate-limit.md
  moralis-server/solana-sdk: moralis-dapp/solana-sdk/README.md
  moralis-server/solana-sdk/intro: moralis-dapp/solana-sdk/intro.md
  moralis-server/solana-sdk/account: moralis-dapp/solana-sdk/account.md
  moralis-server/solana-sdk/nft: moralis-dapp/solana-sdk/nft.md
  moralis-server/automatic-transaction-sync: moralis-dapp/automatic-transaction-sync/README.md
  moralis-server/automatic-transaction-sync/historical-transactions: moralis-dapp/automatic-transaction-sync/historical-transactions.md
  moralis-server/automatic-transaction-sync/smart-contract-events: moralis-dapp/automatic-transaction-sync/smart-contract-events.md
  moralis-server/automatic-transaction-sync/address-casing: moralis-dapp/automatic-transaction-sync/address-casing.md
  moralis-server/database: moralis-dapp/database/README.md
  moralis-server/database/objects: moralis-dapp/database/objects.md
  moralis-server/database/permissions: moralis-dapp/database/permissions.md
  moralis-server/database/queries: moralis-dapp/database/queries.md
  moralis-server/database/bulk-queries: moralis-dapp/database/bulk-queries.md
  moralis-server/database/live-queries: moralis-dapp/database/live-queries.md
  moralis-server/database/roles: moralis-dapp/database/roles.md
  moralis-server/database/security: moralis-dapp/database/security.md
  moralis-server/database/data: moralis-dapp/database/data.md
  moralis-server/database/direct_access: moralis-dapp/database/direct_access.md
  moralis-server/cloud-code: moralis-dapp/cloud-code/README.md
  moralis-server/cloud-code/cloud-functions: moralis-dapp/cloud-code/cloud-functions.md
  moralis-server/cloud-code/httprequest: moralis-dapp/cloud-code/httprequest.md
  moralis-server/cloud-code/triggers: moralis-dapp/cloud-code/triggers.md
  moralis-server/cloud-code/jobs: moralis-dapp/cloud-code/jobs.md
  moralis-server/cloud-code/webhooks: moralis-dapp/cloud-code/webhooks.md
  moralis-server/cloud-code/config: moralis-dapp/cloud-code/config.md
  moralis-server/cloud-code/seamless-updates: moralis-dapp/cloud-code/seamless-updates.md
  moralis-server/web3: moralis-dapp/web3/README.md
  moralis-server/web3/web3: moralis-dapp/web3/web3.md
  moralis-server/web3/setting-up-ganache: moralis-dapp/web3/setting-up-ganache.md
  moralis-server/files: moralis-dapp/files/README.md
  moralis-server/files/files: moralis-dapp/files/files.md
  moralis-server/files/ipfs: moralis-dapp/files/ipfs.md
  moralis-server/tools: moralis-dapp/tools/README.md
  moralis-server/tools/moralis-units: moralis-dapp/tools/moralis-units.md
  moralis-server/tools/moralis-admin-cli: moralis-dapp/tools/moralis-admin-cli.md
  moralis-server/tools/snippets: moralis-dapp/tools/snippets.md
  moralis-server/tools/hosting: moralis-dapp/tools/hosting.md
  moralis-server/plugins: moralis-dapp/plugins/README.md
  moralis-server/plugins/untitled: moralis-dapp/plugins/untitled.md
  moralis-dapp/users/crypto-login: moralis-dapp/users/web3-login.md
  moralis-dapp/users/crypto-login/metamask: moralis-dapp/users/web3-login/metamask.md
  moralis-dapp/users/crypto-login/walletconnect: moralis-dapp/users/web3-login/walletconnect.md
  moralis-dapp/users/crypto-login/web3Auth: moralis-dapp/users/web3-login/web3Auth.md
  moralis-dapp/users/crypto-login/magic: moralis-dapp/users/web3-login/magic.md
  moralis-dapp/users/crypto-login/custom-auth-any-eip1193-provider: moralis-dapp/users/web3-login/custom-auth-any-eip1193-provider.md
  moralis-dapp/users/crypto-login/phantom-solana: moralis-dapp/users/web3-login/phantom-solana.md
  moralis-dapp/users/crypto-login/sign-in-message: moralis-dapp/users/web3-login/sign-in-message.md
  moralis-dapp/web3-sdk: moralis-dapp/web3-api/README.md
  moralis-dapp/web3-sdk/supported-chains: moralis-dapp/web3-api/supported-chains.md
  moralis-dapp/web3-sdk/native: moralis-dapp/web3-api/native.md
  moralis-dapp/web3-sdk/account: moralis-dapp/web3-api/account.md
  moralis-dapp/web3-sdk/token: moralis-dapp/web3-api/token.md
  moralis-dapp/web3-sdk/defi-new: moralis-dapp/web3-api/defi-new.md
  moralis-dapp/web3-sdk/ipfs-storage-new: moralis-dapp/web3-api/ipfs-storage-new.md
  moralis-dapp/web3-sdk/resolve: moralis-dapp/web3-api/resolve.md
  moralis-dapp/web3-sdk/moralis-web3-api-rest: moralis-dapp/web3-api/moralis-web3-api-rest.md
  moralis-dapp/web3-sdk/nft-api: moralis-dapp/web3-api/nft-api.md
  moralis-dapp/web3-sdk/rate-limit: moralis-dapp/web3-api/rate-limit.md
  moralis-dapp/solana-sdk: moralis-dapp/solana-api/README.md
  moralis-dapp/solana-sdk/supported-networks: moralis-dapp/solana-api/supported-networks.md
  moralis-dapp/solana-sdk/account: moralis-dapp/solana-api/account.md
  moralis-dapp/solana-sdk/nft: moralis-dapp/solana-api/nft.md
  unity: moralis-dapp/connect-the-sdk/connect-with-unity.md
  contribute: introduction/contribute-to-docs.md
  community: introduction/our-community.md
  moralis: README.md
